import 'package:flutter/material.dart';
import 'package:studybunnies/adminwidgets/appbar.dart';
import 'package:studybunnies/adminwidgets/bottomnav.dart';
import 'package:studybunnies/adminwidgets/drawer.dart';

class Classlist extends StatefulWidget {
  const Classlist({super.key});

  @override
  State<Classlist> createState() => _ClasslistState();
}

class _ClasslistState extends State<Classlist> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: mainappbar("Classes", "This interface will display the list of classes generated by Admin.", context),
      bottomNavigationBar: navbar(3),
      drawer: adminDrawer(context , 2),
      body: Center(child:Text("Page3"),),
    );
  }
}